---
- name: Server build request
  local_action:
    module: rax
    name: "{{ server_name }}" 
    flavor: "{{ flavor }}" 
    image: "{{ image }}" 
    key_name: "{{ key_name }}" 
    credentials: "{{ credentials }}"
    env: "{{ nova_environment }}"
    wait: yes
  register: rax

- name: Add the instance we created (by public IP) to the group 'devstack-test'
  local_action:
    module: add_host
    hostname: "{{ item.name }}"
    ansible_connection: ssh
    ansible_ssh_host: "{{ item.rax_accessipv4 }}"
    ansible_ssh_user: root
#   ansible_ssh_pass: "{{ item.rax_adminpass }}"
    groupname: devstack-test 
  with_items: rax.success
  when: rax.action == 'create'

- name: Wait for SSH to appear on the new instance.
  local_action:
      module: wait_for
      port: 22 
      host: "{{ item.rax_accessipv4 }}"
  with_items: rax.success
  when: rax.action == 'create'
